spring:
  datasource:
    url: jdbc:sqlserver://datasb.database.windows.net:1433;database=springdb;user=admin123@datasb;password=admin@123;encrypt=true;trustServerCertificate=false;hostNameInCerificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

